#! /bin/bash

set -e

function install_ohmyzsh() {
    # Install Oh My Zsh
    if [ -d ~/.oh-my-zsh ]; then
        echo "Oh My Zsh already installed"
    else
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi

    # Install plugins
    if [ -d ~/.oh-my-zsh ]; then
        zsh_custom_dir="${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}"

        if [ -d "$zsh_custom_dir/plugins/zsh-completions" ]; then
            echo "zsh-completions already installed"
        else
            git clone https://github.com/zsh-users/zsh-completions "$zsh_custom_dir/plugins/zsh-completions"
        fi

        if [ -d "$zsh_custom_dir/plugins/zsh-autosuggestions" ]; then
            echo "zsh-autosuggestions already installed"
        else
            git clone https://github.com/zsh-users/zsh-autosuggestions "$zsh_custom_dir/plugins/zsh-autosuggestions"
        fi

        if [ -d "$zsh_custom_dir/plugins/zsh-syntax-highlighting" ]; then
            echo "zsh-syntax-highlighting already installed"
        else
            git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$zsh_custom_dir/plugins/zsh-syntax-highlighting"
        fi
    fi

    # Import the zshrc
    if [ -f ~/.zshrc ] && grep -qF "source ~/.dotrc/shellrc" ~/.zshrc; then
        echo "zshrc already sourced in ~/.zshrc"
    else
        echo "source ~/.dotrc/shellrc" | tee -a ~/.zshrc
    fi
}

function install_ohmybash() {
    # Install Oh My Bash
    if [ -d ~/.oh-my-bash ]; then
        echo "Oh My Bash already installed"
    else
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
    fi

    # Import the bashrc
    if [ -f ~/.bashrc ] && grep -qF "source ~/.dotrc/shellrc" ~/.bashrc; then
        echo "bashrc already sourced in ~/.bashrc"
    else
        echo "source ~/.dotrc/shellrc" | tee -a ~/.bashrc
    fi
}

function main() {
    install_ohmyzsh
    install_ohmybash
}

main
