#! /bin/bash

set -e

# Import the vimrc
if [ -f ~/.vimrc ] && grep -qF "source ~/.dotrc/vimrc" ~/.vimrc; then
    echo "vimrc already sourced in ~/.vimrc"
else
    echo "source ~/.dotrc/vimrc" | tee -a ~/.vimrc
fi

# Install Vundle
mkdir -p "$HOME/.vim/bundle"

if [ -d "$HOME/.vim/bundle/Vundle.vim" ]; then
    echo "Vundle already installed"
else
    git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
fi

if [ -d "$HOME/.vim/bundle/Vundle.vim" ]; then
    vim +PluginInstall +qall
fi
