#! /bin/bash

set -e

mkdir -p "$HOME/.tmux/plugins"

if [ -d "$HOME/.tmux/plugins/tpm" ]; then
    echo "TPM already installed"
else
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

# Check if tmux.conf contains the line 'source-file ~/.dotrc/tmux.conf'
if [ -f ~/.tmux.conf ] && grep -qF "source-file ~/.dotrc/tmux.conf" ~/.tmux.conf; then
    echo "tmux.conf already sourced in ~/.tmux.conf"
else
    echo "source-file ~/.dotrc/tmux.conf" | tee -a ~/.tmux.conf
fi
